#!/bin/sh
set -e

case "$1" in
    purge)
        # Remove state directory
        rm -rf /run/zviz
        ;;
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;
    *)
        echo "postrm called with unknown argument '$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#
exit 0
